// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using molnsakerhet.Data;

#nullable disable

namespace molnsakerhet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028074516_init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128); // Anpassat för SQL Server

            modelBuilder.Entity("molnsakerhet.Models.Product", b =>
            {
                b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int"); // SQL Server-integer

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)"); // SQL Server nvarchar

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)"); // SQL Server decimal-format

                b.HasKey("ProductId");

                b.ToTable("Products");
            });
#pragma warning restore 612, 618
        }
    }
}
