// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using molnsakerhet.Data;

#nullable disable

namespace molnsakerhet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028083107_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128); // Ändrat till 128 för SQL Server

            // Ta bort PostgreSQL-specifik konfiguration
            // Om det fanns anrop till PostgreSQL-specifika metoder här, ta bort dem

            modelBuilder.Entity("molnsakerhet.Models.Product", b =>
            {
                b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int"); // Ändrat från "integer" till "int"

                // Ta bort Npgsql-specifik kolumnidentitet
                // b.Property<int>("ProductId").UseIdentityByDefaultColumn() 

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)"); // Ändrat till nvarchar(max) för SQL Server

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)"); // Ändrat till nvarchar(max) för SQL Server

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18, 2)"); // Ändrat till decimal(18, 2) för SQL Server

                b.HasKey("ProductId");

                b.ToTable("Products");
            });
#pragma warning restore 612, 618
        }
    }
}
