// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using molnsakerhet.Data;

#nullable disable

namespace molnsakerhet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128); // SQL Server max identifier length

            modelBuilder.Entity("molnsakerhet.Models.Product", b =>
            {
                b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int"); // SQL Server integer type

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)"); // Adjusted for SQL Server

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)"); // SQL Server decimal format

                b.HasKey("ProductId");

                b.ToTable("Products");
            });
#pragma warning restore 612, 618
        }
    }
}
